# Generated by Django 4.1 on 2022-08-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_amount_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PACKED', 'PACKED'), ('TRANSIT', 'TRANSIT'), ('DELIVERED', 'DELIVERED')], default='PACKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
